# Generated by Django 4.2 on 2023-04-12 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("patientapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient",
            name="doctor",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="patient",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="patient",
            name="primary_diagnosis",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="patient",
            name="room",
            field=models.BigIntegerField(default="1"),
        ),
        migrations.AddField(
            model_name="patient",
            name="team",
            field=models.CharField(default="A", max_length=1),
        ),
    ]
