# Generated by Django 4.2 on 2023-04-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patientapi", "0002_patient_date_patient_doctor_patient_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="time",
            field=models.CharField(default="4:26", max_length=5),
        ),
        migrations.AlterField(
            model_name="patient",
            name="date",
            field=models.DateField(default="4/14/2023", max_length=10),
        ),
    ]
