# Generated by Django 4.2 on 2023-04-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patientapi", "0003_patient_time_alter_patient_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="date",
            field=models.CharField(default="4/14/2023", max_length=10),
        ),
        migrations.AlterField(
            model_name="patient",
            name="time",
            field=models.CharField(default="4:27", max_length=5),
        ),
    ]
